apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample
  annotations:
    github.com/project-slug: Meeranmk/portfolio
    scorecard/jsonDataUrl:  https://raw.githubusercontent.com/Meeranmk/score/main/scores.json
    
spec:
  type: service
  lifecycle: production
  owner: guests
  
