apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-service
  namespace: default
  annotations:
    scorecard/jsonDataUrl: https://jsonplaceholder.typicode.com/todos/1
spec:
  type: service
  lifecycle: production
  owner: guests
  
