apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-service
  namespace: default
  annotations:
    scorecard/jsonDataUrl: https://raw.githubusercontent.com/Meeranmk/score/refs/heads/main/scores.json
spec:
  type: service
  lifecycle: production
  owner: guests
  
